### ISSUE TITLE
Year filter wrong granularity?

### ISSUE THREAD

**Issue by winkler1** [SummitRoute/react-structured-filter#1]
Hi,
 Thanks for doing this, it's really cool! I had seen visualsearch and been meaning to try it for react.rocks.

 Date issue:

The IPO column is shown as a year, but the date picker is day level of granularity.

Seems wrong...guess the IPO is really a day, but rounded down to the year? Seems like it'd be more intuitive if the date were displayed.

**Comment by 0xdabbad00** [comment]
Thanks for reaching out to me!  In order to put the demo together, I figured I'd use a different data set than I do in my actual product.  Stock data seemed more easily understandable.  Unfortunately, the stock data set I found only gave years.  So I cheated a bit, by only using the year from the calendar element: https://github.com/SummitRoute/react-structured-filter/blob/master/example/ExampleData.jsx#L1352

I should break out that calendar component and pass it in as a property, so users can more easily choose different components (such as a component that let's them select a time).  

My main goal with this library was to show people how to do custom filtering for Griddle and possibly use my work here as a starting point, and force myself to pull out the functionality I had been using into something more library-ish.
